# .github/dependabot.yml
version: 2
updates:
  # Maintain dependencies for pnpm lockfile and root package.json
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(deps)
      include: scope
    groups:
      root-deps:
        patterns: ['*']
    reviewers:
      - iamvictorli

  # Maintain dependencies for apps/mobile
  - package-ecosystem: npm
    directory: /apps/mobile
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope
    groups:
      mobile-deps:
        patterns: ['*']
    reviewers:
      - iamvictorli

  # Maintain dependencies for apps/web
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope
    groups:
      web-deps:
        patterns: ['*']
    reviewers:
      - iamvictorli

  # Maintain dependencies for packages/state
  - package-ecosystem: npm
    directory: /packages/state
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope
    groups:
      state-deps:
        patterns: ['*']
    reviewers:
      - iamvictorli

  # Maintain dependencies for packages/tsconfig
  - package-ecosystem: npm
    directory: /packages/tsconfig
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope
    groups:
      tsconfig-deps:
        patterns: ['*']
    reviewers:
      - iamvictorli

  # Maintain dependencies for packages/ui-mobile
  - package-ecosystem: npm
    directory: /packages/ui-mobile
    schedule:
      interval: weekly
      time: '04:00'
      timezone: Etc/UTC
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope
    groups:
      ui-mobile-deps:
        patterns: ['*']
    reviewers:
      - iamvictorli
