packages:
  - packages/*
  - apps/*
catalog:
  '@internationalized/date': ^3.8.0
  '@react-native-community/datetimepicker': 8.4.2
  '@types/react': ~19.1.8
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.80.0
  react-redux: ^9.2.0
  rimraf: ^6.0.1
  typescript: ^5.8.3
  vitest: ^3.2.4
