packages:
  - packages/*
  - apps/*
catalog:
  '@internationalized/date': ^3.8.0
  '@react-native-community/datetimepicker': 8.3.0
  '@types/react': ~19.0.14
  react: 19.0.0
  react-dom: 19.0.0
  react-native: 0.79.2
  react-redux: ^9.2.0
  rimraf: ^6.0.1
  typescript: ^5.8.3
  vitest: ^3.2.3
